channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.10.2
  - numpy=1.20.3
  - openpyxl=3.0.7
  - pandas=1.3.2
  - pip=21.0.1
  - pygeos=0.10.2
  - python=3.8.11
  - plotly=5.4.0
  - click=7.1.2
  - bcrypt=3.2.0
  - google-auth=2.3.3
  - python-levenshtein=0.12.2
  - pip:
    - streamlit==1.3.1
    - protobuf==3.17.3
    - gsheetsdb==0.1.13